//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR_DepartmentEntities : DbContext
    {
        private static HR_DepartmentEntities _context;

        public HR_DepartmentEntities()
            : base("name=HR_DepartmentEntities")
        {
        }

        public static HR_DepartmentEntities GetContext()
        {
            if (_context == null)
                _context = new HR_DepartmentEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Воинский_учетСот> Воинский_учетСот { get; set; }
        public virtual DbSet<График_работы> График_работы { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<дополнительные_поля> дополнительные_поля { get; set; }
        public virtual DbSet<Информация_об_организации> Информация_об_организации { get; set; }
        public virtual DbSet<ОбразовниеСот> ОбразовниеСот { get; set; }
        public virtual DbSet<Основания_увольнения> Основания_увольнения { get; set; }
        public virtual DbSet<Отпуска> Отпуска { get; set; }
        public virtual DbSet<Паспортные_данныеСот> Паспортные_данныеСот { get; set; }
        public virtual DbSet<Подразделение> Подразделение { get; set; }
        public virtual DbSet<Приказ_о_переводе> Приказ_о_переводе { get; set; }
        public virtual DbSet<Приказ_о_приеме> Приказ_о_приеме { get; set; }
        public virtual DbSet<Приказ_об_увольнении> Приказ_об_увольнении { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Трудовая_деятельность> Трудовая_деятельность { get; set; }
        public virtual DbSet<Трудовая_книжка> Трудовая_книжка { get; set; }
    }
}
