//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Воинский_учетСот
    {
        public int id { get; set; }
        public int Код_сотрудника { get; set; }
        public string Состав { get; set; }
        public string Категория_годности { get; set; }
        public string Номер_ВУС { get; set; }
        public string Военно_учетная_специальность { get; set; }
        public string Воинское_звание { get; set; }
        public string Категория_запаса { get; set; }
        public string Коммисариат { get; set; }
        public string Спец_учет { get; set; }
        public string Отметка_о_снятии { get; set; }
        public string Общий_учет { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
