//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class дополнительные_поля
    {
        public int id { get; set; }
        public string характер_работы { get; set; }
        public string режим_труда { get; set; }
        public string продолжительность_недели { get; set; }
        public string график_работы { get; set; }
        public Nullable<int> испытательный_срок { get; set; }
        public string вредные_производственные_факторы { get; set; }
        public string основание_приема_на_работу { get; set; }
        public string разряд { get; set; }
        public string квалификационная_категория { get; set; }
        public string работник_подчиняется { get; set; }
        public string место_нахождение_служебного_помещения { get; set; }
        public string обязанности { get; set; }
        public string длительность_отпуска { get; set; }
        public string алфавит { get; set; }
        public int код_сотрудника { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
