//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Информация_об_организации
    {
        public int id { get; set; }
        public string Краткое_название { get; set; }
        public string Полное_наименование { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
        public string ОКПО { get; set; }
        public string Расс__счет { get; set; }
        public string Корр__счет { get; set; }
        public string ОГРН { get; set; }
        public string Рег__номер_в_ПФР { get; set; }
        public string Код_ТО_ПФР { get; set; }
        public string В_банке { get; set; }
        public string БИК_банка { get; set; }
        public string ФИО_Руководителя { get; set; }
        public string Должность_руководителя { get; set; }
        public string ФИО_Главного_бухгалтера { get; set; }
        public string ФИО_работника_кадровой_службы { get; set; }
        public string Должность_работника_кадровой_службы { get; set; }
        public string Телефон_факс { get; set; }
        public string Примечание { get; set; }
    }
}
