//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОбразовниеСот
    {
        public int ID_диплома { get; set; }
        public string ВО_Наименование_документа_об_образовании { get; set; }
        public string ВОСерия { get; set; }
        public string ВОНомер { get; set; }
        public string ВОТип_образования { get; set; }
        public string ВОНаименование_учебного_заведения { get; set; }
        public string ВОСпециальность { get; set; }
        public string ВОКвалификация { get; set; }
        public Nullable<System.DateTime> ВОДата_окончания { get; set; }
        public string Наименование_документа_об_образовании { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
        public string Тип_образования { get; set; }
        public string Наименование_учебного_заведения { get; set; }
        public string Специальность { get; set; }
        public string Квалификация { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public string ПОНаименование { get; set; }
        public string ПОДокумент_ { get; set; }
        public Nullable<System.DateTime> C_ПОДата_выдачи { get; set; }
        public string C_ПОВыдавший_орган { get; set; }
        public string C_ПОУченая_степень { get; set; }
        public string ПОНаправление_по_диплому { get; set; }
        public int Код_сотрудника { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
