//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Основания_увольнения
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Основания_увольнения()
        {
            this.Приказ_об_увольнении = new HashSet<Приказ_об_увольнении>();
        }
    
        public int ID { get; set; }
        public string Статья_ФЗ { get; set; }
        public string Пункт { get; set; }
        public string Основания_увольнения1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Приказ_об_увольнении> Приказ_об_увольнении { get; set; }
    }
}
