//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Паспортные_данныеСот
    {
        public int id { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public string Код_подразделения { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public string Кем_выдан { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public Nullable<System.DateTime> Срок_действия { get; set; }
        public Nullable<System.DateTime> МРДата_регистрации { get; set; }
        public Nullable<System.DateTime> МРСрок_действия_до { get; set; }
        public string МРСтрана { get; set; }
        public string МРРегион { get; set; }
        public string МРПочтовый_индекс { get; set; }
        public string МРГород { get; set; }
        public string МР_Улица { get; set; }
        public string МРДом { get; set; }
        public string МРКорпус { get; set; }
        public string МРКвартира { get; set; }
        public Nullable<System.DateTime> ФПДата_регистрации { get; set; }
        public Nullable<System.DateTime> ФПСрок_действия_до { get; set; }
        public string ФПСтрана { get; set; }
        public string ФПРегион { get; set; }
        public string ФППочтовый_индекс { get; set; }
        public string ФПГород { get; set; }
        public string ФП_Улица { get; set; }
        public string ФПДом { get; set; }
        public string ФПКорпус { get; set; }
        public string ФПКвартира { get; set; }
        public string ВУСерия { get; set; }
        public string ВУНомер { get; set; }
        public Nullable<System.DateTime> ВУСрок_действия_до { get; set; }
        public string ЗПСерия { get; set; }
        public string ЗПНомер { get; set; }
        public Nullable<System.DateTime> ЗПДата_выдачи { get; set; }
        public string ЗПВыдавший_орган { get; set; }
        public Nullable<System.DateTime> ЗПСрок_действия_до { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
