//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приказ_об_увольнении
    {
        public int C__приказа { get; set; }
        public System.DateTime Дата_увольнения { get; set; }
        public string Основание_увольнения { get; set; }
        public string Статья { get; set; }
        public string Пункт { get; set; }
        public string Номер_приказа_на_увольнение { get; set; }
        public System.DateTime Дата_приказа_на_увольнение { get; set; }
        public int Код_сотрудника { get; set; }
        public int IDОснование { get; set; }
    
        public virtual Основания_увольнения Основания_увольнения { get; set; }
    }
}
