//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приказ_о_переводе
    {
        public int C__приакза { get; set; }
        public System.DateTime Дата_утверждения { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_штатной_еденицы { get; set; }
        public string Основание { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
