//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Воинский_учетСот = new HashSet<Воинский_учетСот>();
            this.дополнительные_поля = new HashSet<дополнительные_поля>();
            this.ОбразовниеСот = new HashSet<ОбразовниеСот>();
            this.Отпуска = new HashSet<Отпуска>();
            this.Паспортные_данныеСот = new HashSet<Паспортные_данныеСот>();
            this.Приказ_о_переводе = new HashSet<Приказ_о_переводе>();
            this.Приказ_о_приеме = new HashSet<Приказ_о_приеме>();
            this.Трудовая_деятельность = new HashSet<Трудовая_деятельность>();
            this.Трудовая_книжка = new HashSet<Трудовая_книжка>();
        }
    
        public int Табельный_номер { get; set; }
        public Nullable<System.DateTime> Дата_приема_на_работу { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Пол { get; set; }
        public string Семейное_положение { get; set; }
        public string Телефон_домашний { get; set; }
        public string Телефон_рабочий { get; set; }
        public string Телефон_мобильный { get; set; }
        public string Должность { get; set; }
        public string Отдел { get; set; }
        public string Кабинет { get; set; }
        public string ИНН { get; set; }
        public string СНИЛС { get; set; }
        public string C__мед_полиса { get; set; }
        public string E_mail { get; set; }
        public string Национальность { get; set; }
        public string Гражданство { get; set; }
        public string Место_рождения { get; set; }
        public string название_фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Воинский_учетСот> Воинский_учетСот { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<дополнительные_поля> дополнительные_поля { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОбразовниеСот> ОбразовниеСот { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отпуска> Отпуска { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Паспортные_данныеСот> Паспортные_данныеСот { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Приказ_о_переводе> Приказ_о_переводе { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Приказ_о_приеме> Приказ_о_приеме { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Трудовая_деятельность> Трудовая_деятельность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Трудовая_книжка> Трудовая_книжка { get; set; }
    }
}
