//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Трудовая_деятельность
    {
        public int id { get; set; }
        public int Код_сотрудника { get; set; }
        public Nullable<System.DateTime> Дата_приема_на_работу { get; set; }
        public string Должность { get; set; }
        public string C__договора { get; set; }
        public Nullable<System.DateTime> Дата_договора { get; set; }
        public string C__приказа { get; set; }
        public Nullable<System.DateTime> Дата_приказа { get; set; }
        public Nullable<System.DateTime> Срок_договора { get; set; }
        public string Тип_места_работы { get; set; }
        public string Стаж_работы_общий { get; set; }
        public string Стаж_работы_страховой { get; set; }
        public string Стаж_работы_на_предприятии { get; set; }
        public Nullable<bool> Состоит_в_профсюзе { get; set; }
        public Nullable<double> Оклад { get; set; }
        public Nullable<double> Надбавка { get; set; }
        public Nullable<double> Всего_рублей { get; set; }
        public Nullable<double> Оклад_с_надбавкой { get; set; }
        public Nullable<double> КТУ { get; set; }
        public Nullable<double> Ставка { get; set; }
        public Nullable<double> Чето_рубли_какието_ваще_хз { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
